spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/exchange
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
